namespace AdjuvatorTransductorumRCor
{
    public static class LanguagesCode
    {
        public static readonly Dictionary<string, string> FullLanguageNames = new()
        {
            { "ab", "Abkhazian" },
            { "aa", "Afar" },
            { "af", "Afrikaans" },
            { "ak", "Akan" },
            { "sq", "Albanian" },
            { "am", "Amharic" },
            { "ar", "Arabic" },
            { "an", "Aragonese" },
            { "hy", "Armenian" },
            { "as", "Assamese" },
            { "av", "Avaric" },
            { "ae", "Avestan" },
            { "ay", "Aymara" },
            { "az", "Azerbaijani" },
            { "bm", "Bambara" },
            { "ba", "Bashkir" },
            { "eu", "Basque" },
            { "be", "Belarusian" },
            { "bn", "Bengali" },
            { "bi", "Bislama" },
            { "bs", "Bosnian" },
            { "br", "Breton" },
            { "bg", "Bulgarian" },
            { "my", "Burmese" },
            { "ca", "Catalan, Valencian" },
            { "ch", "Chamorro" },
            { "ce", "Chechen" },
            { "ny", "Chichewa, Chewa, Nyanja" },
            { "zh", "Chinese" },
            { "cu", "Slavonic" },
            { "cv", "Chuvash" },
            { "kw", "Cornish" },
            { "co", "Corsican" },
            { "cr", "Cree" },
            { "hr", "Croatian" },
            { "cs", "Czech" },
            { "da", "Danish" },
            { "dv", "Divehi, Dhivehi, Maldivian" },
            { "nl", "Dutch, Flemish" },
            { "dz", "Dzongkha" },
            { "en", "English" },
            { "eo", "Esperanto" },
            { "et", "Estonian" },
            { "ee", "Ewe" },
            { "fo", "Faroese" },
            { "fj", "Fijian" },
            { "fi", "Finnish" },
            { "fr", "French" },
            { "fy", "Western Frisian" },
            { "ff", "Fulah" },
            { "gd", "Gaelic, Scottish Gaelic" },
            { "gl", "Galician" },
            { "lg", "Ganda" },
            { "ka", "Georgian" },
            { "de", "German" },
            { "el", "Greek" },
            { "kl", "Kalaallisut, Greenlandic" },
            { "gn", "Guarani" },
            { "gu", "Gujarati" },
            { "ht", "Haitian, Haitian Creole" },
            { "ha", "Hausa" },
            { "he", "Hebrew" },
            { "hz", "Herero" },
            { "hi", "Hindi" },
            { "ho", "Hiri Motu" },
            { "hu", "Hungarian" },
            { "is", "Icelandic" },
            { "io", "Ido" },
            { "ig", "Igbo" },
            { "id", "Indonesian" },
            { "ia", "Interlingua" },
            { "ie", "Interlingue, Occidental" },
            { "iu", "Inuktitut" },
            { "ik", "Inupiaq" },
            { "ga", "Irish" },
            { "it", "Italian" },
            { "ja", "Japanese" },
            { "jv", "Javanese" },
            { "kn", "Kannada" },
            { "kr", "Kanuri" },
            { "ks", "Kashmiri" },
            { "kk", "Kazakh" },
            { "km", "Central Khmer" },
            { "ki", "Kikuyu, Gikuyu" },
            { "rw", "Kinyarwanda" },
            { "ky", "Kirghiz, Kyrgyz" },
            { "kv", "Komi" },
            { "kg", "Kongo" },
            { "ko", "Korean" },
            { "kj", "Kuanyama, Kwanyama" },
            { "ku", "Kurdish" },
            { "lo", "Lao" },
            { "la", "Latin" },
            { "lv", "Latvian" },
            { "li", "Limburgish" },
            { "ln", "Lingala" },
            { "lt", "Lithuanian" },
            { "lu", "Luba-Katanga" },
            { "lb", "Luxembourgish" },
            { "mk", "Macedonian" },
            { "mg", "Malagasy" },
            { "ms", "Malay" },
            { "ml", "Malayalam" },
            { "mt", "Maltese" },
            { "gv", "Manx" },
            { "mi", "Maori" },
            { "mr", "Marathi" },
            { "mh", "Marshallese" },
            { "mn", "Mongolian" },
            { "na", "Nauru" },
            { "nv", "Navajo, Navaho" },
            { "nd", "North Ndebele" },
            { "nr", "South Ndebele" },
            { "ng", "Ndonga" },
            { "ne", "Nepali" },
            { "no", "Norwegian" },
            { "nb", "Norwegian Bokmål" },
            { "nn", "Norwegian Nynorsk" },
            { "Yi", "Sichuan" },
            { "oc", "Occitan" },
            { "oj", "Ojibwa" },
            { "or", "Oriya" },
            { "om", "Oromo" },
            { "os", "Ossetian" },
            { "pi", "Pali" },
            { "ps", "Pashto, Pushto" },
            { "fa", "Persian" },
            { "pl", "Polish" },
            { "pt", "Portuguese" },
            { "pa", "Punjabi, Panjabi" },
            { "qu", "Quechua" },
            { "ro", "Romanian, Moldavian, Moldovan" },
            { "rm", "Romansh" },
            { "rn", "Rundi" },
            { "ru", "Russian" },
            { "se", "Northern Sami" },
            { "sm", "Samoan" },
            { "sg", "Sango" },
            { "sa", "Sanskrit" },
            { "sc", "Sardinian" },
            { "sr", "Serbian" },
            { "sn", "Shona" },
            { "sd", "Sindhi" },
            { "si", "Sinhala, Sinhalese" },
            { "sk", "Slovak" },
            { "sl", "Slovenian" },
            { "so", "Somali" },
            { "st", "Southern Sotho" },
            { "es", "Spanish, Castilian" },
            { "su", "Sundanese" },
            { "sw", "Swahili" },
            { "ss", "Swati" },
            { "sv", "Swedish" },
            { "tl", "Tagalog" },
            { "ty", "Tahitian" },
            { "tg", "Tajik" },
            { "ta", "Tamil" },
            { "tt", "Tatar" },
            { "te", "Telugu" },
            { "th", "Thai" },
            { "bo", "Tibetan" },
            { "ti", "Tigrinya" },
            { "to", "Tonga" },
            { "ts", "Tsonga" },
            { "tn", "Tswana" },
            { "tr", "Turkish" },
            { "tk", "Turkmen" },
            { "tw", "Twi" },
            { "ug", "Uighur, Uyghur" },
            { "uk", "Ukrainian" },
            { "ur", "Urdu" },
            { "uz", "Uzbek" },
            { "ve", "Venda" },
            { "vi", "Vietnamese" },
            { "vo", "Volapük" },
            { "wa", "Walloon" },
            { "cy", "Welsh" },
            { "wo", "Wolof" },
            { "xh", "Xhosa" },
            { "yi", "Yiddish" },
            { "yo", "Yoruba" },
            { "za", "Zhuang, Chuang" },
            { "zu", "Zulu" }
        };

        public static readonly Dictionary<string, string> ShortLanguageCodes = new()
        {
            { "Abkhazian", "ab" },
            { "Afar", "aa" },
            { "Afrikaans", "af" },
            { "Akan", "ak" },
            { "Albanian", "sq" },
            { "Amharic", "am" },
            { "Arabic", "ar" },
            { "Aragonese", "an" },
            { "Armenian", "hy" },
            { "Assamese", "as" },
            { "Avaric", "av" },
            { "Avestan", "ae" },
            { "Aymara", "ay" },
            { "Azerbaijani", "az" },
            { "Bambara", "bm" },
            { "Bashkir", "ba" },
            { "Basque", "eu" },
            { "Belarusian", "be" },
            { "Bengali", "bn" },
            { "Bislama", "bi" },
            { "Bosnian", "bs" },
            { "Breton", "br" },
            { "Bulgarian", "bg" },
            { "Burmese", "my" },
            { "Catalan, Valencian", "ca" },
            { "Chamorro", "ch" },
            { "Chechen", "ce" },
            { "Chichewa, Chewa, Nyanja", "ny" },
            { "Chinese", "zh" },
            { "Slavonic", "cu" },
            { "Chuvash", "cv" },
            { "Cornish", "kw" },
            { "Corsican", "co" },
            { "Cree", "cr" },
            { "Croatian", "hr" },
            { "Czech", "cs" },
            { "Danish", "da" },
            { "Divehi, Dhivehi, Maldivian", "dv" },
            { "Dutch, Flemish", "nl" },
            { "Dzongkha", "dz" },
            { "English", "en" },
            { "Esperanto", "eo" },
            { "Estonian", "et" },
            { "Ewe", "ee" },
            { "Faroese", "fo" },
            { "Fijian", "fj" },
            { "Finnish", "fi" },
            { "French", "fr" },
            { "Western Frisian", "fy" },
            { "Fulah", "ff" },
            { "Gaelic, Scottish Gaelic", "gd" },
            { "Galician", "gl" },
            { "Ganda", "lg" },
            { "Georgian", "ka" },
            { "German", "de" },
            { "Greek", "el" },
            { "Kalaallisut, Greenlandic", "kl" },
            { "Guarani", "gn" },
            { "Gujarati", "gu" },
            { "Haitian, Haitian Creole", "ht" },
            { "Hausa", "ha" },
            { "Hebrew", "he" },
            { "Herero", "hz" },
            { "Hindi", "hi" },
            { "Hiri Motu", "ho" },
            { "Hungarian", "hu" },
            { "Icelandic", "is" },
            { "Ido", "io" },
            { "Igbo", "ig" },
            { "Indonesian", "id" },
            { "Interlingua", "ia" },
            { "Interlingue, Occidental", "ie" },
            { "Inuktitut", "iu" },
            { "Inupiaq", "ik" },
            { "Irish", "ga" },
            { "Italian", "it" },
            { "Japanese", "ja" },
            { "Javanese", "jv" },
            { "Kannada", "kn" },
            { "Kanuri", "kr" },
            { "Kashmiri", "ks" },
            { "Kazakh", "kk" },
            { "Central Khmer", "km" },
            { "Kikuyu, Gikuyu", "ki" },
            { "Kinyarwanda", "rw" },
            { "Kirghiz, Kyrgyz", "ky" },
            { "Komi", "kv" },
            { "Kongo", "kg" },
            { "Korean", "ko" },
            { "Kuanyama, Kwanyama", "kj" },
            { "Kurdish", "ku" },
            { "Lao", "lo" },
            { "Latin", "la" },
            { "Latvian", "lv" },
            { "Limburgish", "li" },
            { "Lingala", "ln" },
            { "Lithuanian", "lt" },
            { "Luba-Katanga", "lu" },
            { "Luxembourgish", "lb" },
            { "Macedonian", "mk" },
            { "Malagasy", "mg" },
            { "Malay", "ms" },
            { "Malayalam", "ml" },
            { "Maltese", "mt" },
            { "Manx", "gv" },
            { "Maori", "mi" },
            { "Marathi", "mr" },
            { "Marshallese", "mh" },
            { "Mongolian", "mn" },
            { "Nauru", "na" },
            { "Navajo, Navaho", "nv" },
            { "North Ndebele", "nd" },
            { "South Ndebele", "nr" },
            { "Ndonga", "ng" },
            { "Nepali", "ne" },
            { "Norwegian", "no" },
            { "Norwegian Bokmål", "nb" },
            { "Norwegian Nynorsk", "nn" },
            { "Sichuan", "Yi" },
            { "Occitan", "oc" },
            { "Ojibwa", "oj" },
            { "Oriya", "or" },
            { "Oromo", "om" },
            { "Ossetian", "os" },
            { "Pali", "pi" },
            { "Pashto, Pushto", "ps" },
            { "Persian", "fa" },
            { "Polish", "pl" },
            { "Portuguese", "pt" },
            { "Punjabi, Panjabi", "pa" },
            { "Quechua", "qu" },
            { "Romanian, Moldavian, Moldovan", "ro" },
            { "Romansh", "rm" },
            { "Rundi", "rn" },
            { "Russian", "ru" },
            { "Northern Sami", "se" },
            { "Samoan", "sm" },
            { "Sango", "sg" },
            { "Sanskrit", "sa" },
            { "Sardinian", "sc" },
            { "Serbian", "sr" },
            { "Shona", "sn" },
            { "Sindhi", "sd" },
            { "Sinhala, Sinhalese", "si" },
            { "Slovak", "sk" },
            { "Slovenian", "sl" },
            { "Somali", "so" },
            { "Southern Sotho", "st" },
            { "Spanish, Castilian", "es" },
            { "Sundanese", "su" },
            { "Swahili", "sw" },
            { "Swati", "ss" },
            { "Swedish", "sv" },
            { "Tagalog", "tl" },
            { "Tahitian", "ty" },
            { "Tajik", "tg" },
            { "Tamil", "ta" },
            { "Tatar", "tt" },
            { "Telugu", "te" },
            { "Thai", "th" },
            { "Tibetan", "bo" },
            { "Tigrinya", "ti" },
            { "Tonga", "to" },
            { "Tsonga", "ts" },
            { "Tswana", "tn" },
            { "Turkish", "tr" },
            { "Turkmen", "tk" },
            { "Twi", "tw" },
            { "Uighur, Uyghur", "ug" },
            { "Ukrainian", "uk" },
            { "Urdu", "ur" },
            { "Uzbek", "uz" },
            { "Venda", "ve" },
            { "Vietnamese", "vi" },
            { "Volapük", "vo" },
            { "Walloon", "wa" },
            { "Welsh", "cy" },
            { "Wolof", "wo" },
            { "Xhosa", "xh" },
            { "Yiddish", "yi" },
            { "Yoruba", "yo" },
            { "Zhuang, Chuang", "za" },
            { "Zulu", "zu" }
        };
    }
}
